definitions:
  main.ErrorResponse:
    properties:
      message:
        description: Error es el mensaje de error
        type: string
    type: object
  main.Series:
    properties:
      id:
        description: ID es el identificador único de la serie
        type: integer
      lastEpisodeWatched:
        description: LastEpisodeWatched es el último episodio visto por el usuario
        type: integer
      ranking:
        description: Ranking es la calificación de la serie
        type: integer
      status:
        description: Status es el estado de la serie (e.g., "Plan to Watch", "Watching",
          "Dropped", "Completed")
        type: string
      title:
        description: Title es el título de la serie
        type: string
      totalEpisodes:
        description: TotalEpisodes es el total de episodios de la serie
        type: integer
    type: object
  main.SuccessResponse:
    properties:
      message:
        description: Message es el mensaje de éxito
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gestionar series de televisión
  title: Series Tracker API
  version: "1.0"
paths:
  /api/series:
    get:
      description: Obtiene una lista de todas las series en la base de datos
      parameters:
      - description: Buscar por título
        in: query
        name: search
        type: string
      - description: Filtrar por estado (e.g., 'Watching', 'Completed')
        enum:
        - Watching
        - Completed
        - Dropped
        - PlanToWatch
        in: query
        name: status
        type: string
      - description: Ordenar por (e.g., 'asc', 'desc')
        enum:
        - asc
        - desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de series
          schema:
            items:
              $ref: '#/definitions/main.Series'
            type: array
      summary: Obtener todas las series
      tags:
      - series
    post:
      description: Crea una nueva serie en la base de datos
      parameters:
      - description: Datos de la serie
        in: body
        name: series
        required: true
        schema:
          $ref: '#/definitions/main.Series'
      produces:
      - application/json
      responses:
        "200":
          description: Serie creada
          schema:
            type: string
      summary: Crear una nueva serie
      tags:
      - series
  /api/series/{id}:
    delete:
      description: Elimina una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Serie eliminada
          schema:
            $ref: '#/definitions/main.SuccessResponse'
        "404":
          description: Error al eliminar la serie
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Eliminar una serie por ID
      tags:
      - series
    get:
      description: Obtiene una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Serie encontrada
          schema:
            $ref: '#/definitions/main.Series'
        "404":
          description: Serie no encontrada
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Obtener una serie por ID
      tags:
      - series
    put:
      description: Actualiza una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      - description: Datos de la serie
        in: body
        name: series
        required: true
        schema:
          $ref: '#/definitions/main.Series'
      produces:
      - application/json
      responses:
        "200":
          description: Serie actualizada
          schema:
            $ref: '#/definitions/main.SuccessResponse'
      summary: Actualizar una serie por ID
      tags:
      - series
  /api/series/{id}/downvote:
    patch:
      description: Disminuye el ranking de una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ranking actualizado
          schema:
            $ref: '#/definitions/main.SuccessResponse'
        "404":
          description: Serie no encontrada
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Disminuir el ranking de una serie por ID
      tags:
      - series
  /api/series/{id}/episode:
    patch:
      description: Actualiza el episodio de una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Episodio actualizado
          schema:
            $ref: '#/definitions/main.SuccessResponse'
        "404":
          description: Serie no encontrada
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Actualizar el episodio de una serie por ID
      tags:
      - series
  /api/series/{id}/status:
    patch:
      description: Actualiza el estado de una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      - description: Nuevo estado de la serie (e.g., 'Watching', 'Completed')
        enum:
        - Watching
        - Completed
        - Dropped
        - PlanToWatch
        in: query
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Estado actualizado
          schema:
            $ref: '#/definitions/main.SuccessResponse'
        "404":
          description: Serie no encontrada
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Actualizar el estado de una serie por ID
      tags:
      - series
  /api/series/{id}/upvote:
    patch:
      description: Aumenta el ranking de una serie específica por su ID
      parameters:
      - description: ID de la serie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ranking actualizado
          schema:
            $ref: '#/definitions/main.SuccessResponse'
        "404":
          description: Serie no encontrada
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Aumentar el ranking de una serie por ID
      tags:
      - series
schemes:
- http
swagger: "2.0"
